package ProyectoFinal;
import Proyecto.*;
import Parcial_2.*;
import java.awt.Toolkit;

public class Figuras extends javax.swing.JFrame {
    
     static P2Proyecto P2 = new P2Proyecto();
     
    public Figuras() {
        initComponents();
        this.setLocationRelativeTo(null);
        TrasparenciaBoton();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFiguras = new javax.swing.JLabel();
        jButtonSalida = new javax.swing.JButton();
        jLabelFigura1 = new javax.swing.JLabel();
        jButtonFigura1For = new javax.swing.JButton();
        jButtonFigura1While = new javax.swing.JButton();
        jButtonFigura1DoWhile = new javax.swing.JButton();
        jLabelFigura2 = new javax.swing.JLabel();
        jButtonFigura2For = new javax.swing.JButton();
        jButtonFigura2While = new javax.swing.JButton();
        jButtonFigura2DoWhile = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        JButtonLImpiar = new javax.swing.JButton();
        jLabelRegresar = new javax.swing.JLabel();
        jLabelLimpiar = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jLabelFigura = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFiguras.setFont(new java.awt.Font("MS PGothic", 0, 18)); // NOI18N
        jLabelFiguras.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFiguras.setText("Tipos de Figuras:");
        getContentPane().add(jLabelFiguras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButtonSalida.setBackground(new java.awt.Color(204, 0, 51));
        jButtonSalida.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonSalida.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalida.setText("X");
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        jLabelFigura1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelFigura1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFigura1.setText("Figura 1:");
        getContentPane().add(jLabelFigura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 30));

        jButtonFigura1For.setBackground(new java.awt.Color(0, 102, 255));
        jButtonFigura1For.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonFigura1For.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFigura1For.setText("Ciclo For");
        jButtonFigura1For.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFigura1ForActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFigura1For, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jButtonFigura1While.setBackground(new java.awt.Color(204, 0, 204));
        jButtonFigura1While.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonFigura1While.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFigura1While.setText("Ciclo While");
        jButtonFigura1While.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFigura1WhileActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFigura1While, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jButtonFigura1DoWhile.setBackground(new java.awt.Color(0, 51, 102));
        jButtonFigura1DoWhile.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonFigura1DoWhile.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFigura1DoWhile.setText("Ciclo Do-While");
        jButtonFigura1DoWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFigura1DoWhileActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFigura1DoWhile, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 170, 40));

        jLabelFigura2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelFigura2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFigura2.setText("Figura 2:");
        getContentPane().add(jLabelFigura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, 30));

        jButtonFigura2For.setBackground(new java.awt.Color(255, 153, 0));
        jButtonFigura2For.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonFigura2For.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFigura2For.setText("Ciclo For");
        jButtonFigura2For.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFigura2ForActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFigura2For, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jButtonFigura2While.setBackground(new java.awt.Color(51, 204, 0));
        jButtonFigura2While.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonFigura2While.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFigura2While.setText("Ciclo While");
        jButtonFigura2While.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFigura2WhileActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFigura2While, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jButtonFigura2DoWhile.setBackground(new java.awt.Color(204, 51, 0));
        jButtonFigura2DoWhile.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonFigura2DoWhile.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFigura2DoWhile.setText("Ciclo Do While");
        jButtonFigura2DoWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFigura2DoWhileActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFigura2DoWhile, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 142, -1, -1));

        JButtonLImpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.png"))); // NOI18N
        JButtonLImpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonLImpiarActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonLImpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 80, -1));

        jLabelRegresar.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabelRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegresar.setText("Regresar");
        getContentPane().add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabelLimpiar.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabelLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLimpiar.setText("Limpiar");
        getContentPane().add(jLabelLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        jLabelFondo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iPhone_png by Kyle Gray.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 728, 210));

        jLabelFigura.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabelFigura.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFigura.setText("Figura:");
        getContentPane().add(jLabelFigura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        JTA.setBackground(new java.awt.Color(0, 102, 102));
        JTA.setColumns(20);
        JTA.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JTA.setForeground(new java.awt.Color(255, 255, 255));
        JTA.setRows(5);
        jScrollPane1.setViewportView(JTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 728, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void   TrasparenciaBoton(){
        jButtonBack.setOpaque(false);
        jButtonBack.setContentAreaFilled(false);
        jButtonBack.setBorderPainted(false);
        
        JButtonLImpiar.setOpaque(false);
        JButtonLImpiar.setContentAreaFilled(false);
        JButtonLImpiar.setBorderPainted(false);
    }
    
    private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalidaActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.setVisible(false);
        Menu M = new Menu();
        M.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void JButtonLImpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonLImpiarActionPerformed
        String salida=""+"Figura:";
        JTA.setText(salida);

    }//GEN-LAST:event_JButtonLImpiarActionPerformed

    private void jButtonFigura1ForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFigura1ForActionPerformed
        String salida="";
        CB_Figura1 F1=new CB_Figura1();
        salida = F1.Figura1FOR();
        JTA.setText(salida);
    }//GEN-LAST:event_jButtonFigura1ForActionPerformed

    private void jButtonFigura2ForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFigura2ForActionPerformed
        String salida="";
        CB_Figura2 F2=new CB_Figura2();
        salida = F2.FiguraFOR();
        JTA.setText(salida);
    }//GEN-LAST:event_jButtonFigura2ForActionPerformed

    private void jButtonFigura1WhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFigura1WhileActionPerformed
        String salida="";
        CB_Figura1 F1=new CB_Figura1();
        salida = F1.Figura1WHILE();
        JTA.setText(salida);
    }//GEN-LAST:event_jButtonFigura1WhileActionPerformed

    private void jButtonFigura1DoWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFigura1DoWhileActionPerformed
        String salida="";
        CB_Figura1 F1=new CB_Figura1();
        salida = F1.Figura1DOWHILE();
        JTA.setText(salida);
    }//GEN-LAST:event_jButtonFigura1DoWhileActionPerformed

    private void jButtonFigura2WhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFigura2WhileActionPerformed
        String salida="";
        CB_Figura2 F2=new CB_Figura2();
        salida = F2.FiguraWHILE();
        JTA.setText(salida);
    }//GEN-LAST:event_jButtonFigura2WhileActionPerformed

    private void jButtonFigura2DoWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFigura2DoWhileActionPerformed
        String salida="";
        CB_Figura2 F2=new CB_Figura2();
        salida = F2.FiguraDOWHILE();
        JTA.setText(salida);
    }//GEN-LAST:event_jButtonFigura2DoWhileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Figuras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonLImpiar;
    private javax.swing.JTextArea JTA;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonFigura1DoWhile;
    private javax.swing.JButton jButtonFigura1For;
    private javax.swing.JButton jButtonFigura1While;
    private javax.swing.JButton jButtonFigura2DoWhile;
    private javax.swing.JButton jButtonFigura2For;
    private javax.swing.JButton jButtonFigura2While;
    private javax.swing.JButton jButtonSalida;
    private javax.swing.JLabel jLabelFigura;
    private javax.swing.JLabel jLabelFigura1;
    private javax.swing.JLabel jLabelFigura2;
    private javax.swing.JLabel jLabelFiguras;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLimpiar;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
