package ProyectoFinal;
import java.awt.Toolkit;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMenuTitulo = new javax.swing.JLabel();
        jButtonCalculoDias = new javax.swing.JButton();
        jButtonCalificaciones = new javax.swing.JButton();
        jButtonFiguras = new javax.swing.JButton();
        jButtonSalida = new javax.swing.JButton();
        jLabelFondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMenuTitulo.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabelMenuTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenuTitulo.setText("MENÚ");
        getContentPane().add(jLabelMenuTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jButtonCalculoDias.setBackground(new java.awt.Color(0, 51, 102));
        jButtonCalculoDias.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonCalculoDias.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalculoDias.setText("Calculo de Días");
        jButtonCalculoDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculoDiasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalculoDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jButtonCalificaciones.setBackground(new java.awt.Color(0, 51, 102));
        jButtonCalificaciones.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonCalificaciones.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalificaciones.setText("Calificaciones");
        jButtonCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalificacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jButtonFiguras.setBackground(new java.awt.Color(0, 51, 102));
        jButtonFiguras.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonFiguras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFiguras.setText("Figuras");
        jButtonFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFigurasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFiguras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jButtonSalida.setBackground(new java.awt.Color(204, 0, 51));
        jButtonSalida.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonSalida.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalida.setText("X");
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabelFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dibujo Sobre Un Fondo Azul.jpg"))); // NOI18N
        jLabelFondoMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalidaActionPerformed

    private void jButtonCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalificacionesActionPerformed
        this.setVisible(false);
        Calificaciones C = new Calificaciones();
        C.setVisible(true);
    }//GEN-LAST:event_jButtonCalificacionesActionPerformed

    private void jButtonCalculoDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculoDiasActionPerformed
        this.setVisible(false);
        CalculoDias CD = new CalculoDias();
        CD.setVisible(true);
    }//GEN-LAST:event_jButtonCalculoDiasActionPerformed

    private void jButtonFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFigurasActionPerformed
        this.setVisible(false);
        Figuras F1 = new Figuras();
        F1.setVisible(true);
    }//GEN-LAST:event_jButtonFigurasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculoDias;
    private javax.swing.JButton jButtonCalificaciones;
    private javax.swing.JButton jButtonFiguras;
    private javax.swing.JButton jButtonSalida;
    private javax.swing.JLabel jLabelFondoMenu;
    private javax.swing.JLabel jLabelMenuTitulo;
    // End of variables declaration//GEN-END:variables
}
