package Proyecto;
import Parcial_2.*;
import java.awt.Toolkit;

public class P2_Figuras extends javax.swing.JFrame {
    
     static P2Proyecto P2 = new P2Proyecto();
     
    public P2_Figuras() {
        initComponents();
        this.setLocationRelativeTo(null);
        TrasparenciaBoton();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFiguras = new javax.swing.JLabel();
        jButtonSalida = new javax.swing.JButton();
        jButtonFigura001 = new javax.swing.JButton();
        jButtonFigura002 = new javax.swing.JButton();
        jButtonFigura003 = new javax.swing.JButton();
        jButtonFigura004 = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        JButtonLImpiar = new javax.swing.JButton();
        jLabelRegresar = new javax.swing.JLabel();
        jLabelLimpiar = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jLabelFigura = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFiguras.setFont(new java.awt.Font("MS PGothic", 0, 18)); // NOI18N
        jLabelFiguras.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFiguras.setText("Tipos de Figuras:");
        getContentPane().add(jLabelFiguras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButtonSalida.setBackground(new java.awt.Color(204, 0, 51));
        jButtonSalida.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonSalida.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalida.setText("X");
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        jButtonFigura001.setBackground(new java.awt.Color(0, 102, 255));
        jButtonFigura001.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonFigura001.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFigura001.setText("Figura 001");
        jButtonFigura001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFigura001ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFigura001, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jButtonFigura002.setBackground(new java.awt.Color(255, 153, 0));
        jButtonFigura002.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonFigura002.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFigura002.setText("Figura 002");
        jButtonFigura002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFigura002ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFigura002, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jButtonFigura003.setBackground(new java.awt.Color(0, 204, 51));
        jButtonFigura003.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonFigura003.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFigura003.setText("Figura 003");
        jButtonFigura003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFigura003ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFigura003, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jButtonFigura004.setBackground(new java.awt.Color(102, 0, 102));
        jButtonFigura004.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonFigura004.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFigura004.setText("Figura 004");
        jButtonFigura004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFigura004ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFigura004, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 142, -1, -1));

        JButtonLImpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.png"))); // NOI18N
        JButtonLImpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonLImpiarActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonLImpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 80, -1));

        jLabelRegresar.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabelRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegresar.setText("Regresar");
        getContentPane().add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabelLimpiar.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabelLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLimpiar.setText("Limpiar");
        getContentPane().add(jLabelLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        jLabelFondo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iPhone_png by Kyle Gray.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 728, 210));

        jLabelFigura.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabelFigura.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFigura.setText("Figura:");
        getContentPane().add(jLabelFigura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        JTA.setBackground(new java.awt.Color(0, 102, 102));
        JTA.setColumns(20);
        JTA.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JTA.setForeground(new java.awt.Color(255, 255, 255));
        JTA.setRows(5);
        jScrollPane1.setViewportView(JTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 728, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void   TrasparenciaBoton(){
        jButtonBack.setOpaque(false);
        jButtonBack.setContentAreaFilled(false);
        jButtonBack.setBorderPainted(false);
        
        JButtonLImpiar.setOpaque(false);
        JButtonLImpiar.setContentAreaFilled(false);
        JButtonLImpiar.setBorderPainted(false);
    }
    
    private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalidaActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.setVisible(false);
        PantallaMenuParcial2 PMP2 = new PantallaMenuParcial2();
        PMP2.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void JButtonLImpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonLImpiarActionPerformed
        String salida=""+"Figura:";
        JTA.setText(salida);

    }//GEN-LAST:event_JButtonLImpiarActionPerformed

    private void jButtonFigura004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFigura004ActionPerformed
         String salida="";
        salida = P2.Figura004();
        JTA.setText(salida);
    }//GEN-LAST:event_jButtonFigura004ActionPerformed

    private void jButtonFigura001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFigura001ActionPerformed
        String salida="";
        salida = P2.Figura001();
        JTA.setText(salida);
    }//GEN-LAST:event_jButtonFigura001ActionPerformed

    private void jButtonFigura002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFigura002ActionPerformed
         String salida="";
        salida = P2.Figura002();
        JTA.setText(salida);
    }//GEN-LAST:event_jButtonFigura002ActionPerformed

    private void jButtonFigura003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFigura003ActionPerformed
         String salida="";
        salida = P2.Figura003();
        JTA.setText(salida);
    }//GEN-LAST:event_jButtonFigura003ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P2_Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P2_Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P2_Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P2_Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P2_Figuras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonLImpiar;
    private javax.swing.JTextArea JTA;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonFigura001;
    private javax.swing.JButton jButtonFigura002;
    private javax.swing.JButton jButtonFigura003;
    private javax.swing.JButton jButtonFigura004;
    private javax.swing.JButton jButtonSalida;
    private javax.swing.JLabel jLabelFigura;
    private javax.swing.JLabel jLabelFiguras;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLimpiar;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
