package Proyecto;
import Parcial_2.*;
import java.awt.Toolkit;

public class P2_Tabla extends javax.swing.JFrame {
    static P2Proyecto P2 = new P2Proyecto();
    
    public P2_Tabla() {
        initComponents();
        this.setLocationRelativeTo(null);
        TrasparenciaBoton();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalida = new javax.swing.JButton();
        jLabelDatos = new javax.swing.JLabel();
        jLabelTablaInicial = new javax.swing.JLabel();
        jLabelTablaFinal = new javax.swing.JLabel();
        jLabelLimpiar = new javax.swing.JLabel();
        jLabelRegresar = new javax.swing.JLabel();
        jTextFieldTablaInicial = new javax.swing.JTextField();
        jTextFieldTablaFinal = new javax.swing.JTextField();
        jButtonInico = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        JButtonLImpiar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();
        jLabelTabla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalida.setBackground(new java.awt.Color(204, 0, 51));
        jButtonSalida.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonSalida.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalida.setText("X");
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 10, 50, 30));

        jLabelDatos.setFont(new java.awt.Font("MS PGothic", 0, 18)); // NOI18N
        jLabelDatos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDatos.setText("Datos:");
        getContentPane().add(jLabelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabelTablaInicial.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelTablaInicial.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTablaInicial.setText("Tabla Inicial:");
        getContentPane().add(jLabelTablaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabelTablaFinal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelTablaFinal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTablaFinal.setText("Tabla Final:");
        getContentPane().add(jLabelTablaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, 20));

        jLabelLimpiar.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabelLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLimpiar.setText("Limpiar");
        getContentPane().add(jLabelLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, -1));

        jLabelRegresar.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabelRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegresar.setText("Regresar");
        getContentPane().add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jTextFieldTablaInicial.setBackground(new java.awt.Color(153, 255, 255));
        jTextFieldTablaInicial.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextFieldTablaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 120, 20));

        jTextFieldTablaFinal.setBackground(new java.awt.Color(153, 255, 255));
        jTextFieldTablaFinal.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldTablaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTablaFinalActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTablaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 120, -1));

        jButtonInico.setBackground(new java.awt.Color(51, 102, 255));
        jButtonInico.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonInico.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInico.setText("Iniciar Programa");
        jButtonInico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInico, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, 50));

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 142, -1, -1));

        JButtonLImpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.png"))); // NOI18N
        JButtonLImpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonLImpiarActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonLImpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 80, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iPhone_png by Kyle Gray.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 728, 210));

        jLabelTabla.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabelTabla.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTabla.setText("Tablas:");
        getContentPane().add(jLabelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        JTA.setBackground(new java.awt.Color(0, 102, 102));
        JTA.setColumns(20);
        JTA.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        JTA.setForeground(new java.awt.Color(255, 255, 255));
        JTA.setRows(5);
        jScrollPane1.setViewportView(JTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 728, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void   TrasparenciaBoton(){
        jButtonBack.setOpaque(false);
        jButtonBack.setContentAreaFilled(false);
        jButtonBack.setBorderPainted(false);
        
        JButtonLImpiar.setOpaque(false);
        JButtonLImpiar.setContentAreaFilled(false);
        JButtonLImpiar.setBorderPainted(false);
    }
    
    private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalidaActionPerformed

    private void jButtonInicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicoActionPerformed
        int inicio = Integer.parseInt(jTextFieldTablaInicial.getText());
        int fin = Integer.parseInt(jTextFieldTablaFinal.getText());
        String salida="";
        salida = P2.TablasMultiplicarFOR(inicio,fin);
        JTA.setText(salida);
    }//GEN-LAST:event_jButtonInicoActionPerformed

    private void jTextFieldTablaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTablaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTablaFinalActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.setVisible(false);
        PantallaMenuParcial2 PMP2 = new PantallaMenuParcial2();
        PMP2.setVisible(true);  
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void JButtonLImpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonLImpiarActionPerformed
        String salida=""+"Tablas:";
        JTA.setText(salida);
        jTextFieldTablaInicial.setText("");
        jTextFieldTablaFinal.setText("");
    }//GEN-LAST:event_JButtonLImpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P2_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P2_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P2_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P2_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P2_Tabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonLImpiar;
    private javax.swing.JTextArea JTA;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonInico;
    private javax.swing.JButton jButtonSalida;
    private javax.swing.JLabel jLabelDatos;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLimpiar;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelTabla;
    private javax.swing.JLabel jLabelTablaFinal;
    private javax.swing.JLabel jLabelTablaInicial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldTablaFinal;
    private javax.swing.JTextField jTextFieldTablaInicial;
    // End of variables declaration//GEN-END:variables
}
