package Proyecto;

import java.awt.Toolkit;

public class PantallaMenuParcial2 extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMenuParcial2
     */
    public PantallaMenuParcial2() {
        initComponents();
        this.setLocationRelativeTo(null);
        TrasparenciaBoton();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalida = new javax.swing.JButton();
        jButtonTablas = new javax.swing.JButton();
        jButtonFiguras = new javax.swing.JButton();
        NumerosLetras = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonPagar = new javax.swing.JButton();
        jButtonBillete = new javax.swing.JButton();
        jLabelParcial2 = new javax.swing.JLabel();
        jLabelFondoParcial2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalida.setBackground(new java.awt.Color(204, 0, 51));
        jButtonSalida.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonSalida.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalida.setText("X");
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jButtonTablas.setBackground(new java.awt.Color(0, 51, 102));
        jButtonTablas.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonTablas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTablas.setText("Tablas");
        jButtonTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTablasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, -1));

        jButtonFiguras.setBackground(new java.awt.Color(0, 51, 102));
        jButtonFiguras.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonFiguras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFiguras.setText("Figuras");
        jButtonFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFigurasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFiguras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        NumerosLetras.setBackground(new java.awt.Color(0, 51, 102));
        NumerosLetras.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        NumerosLetras.setForeground(new java.awt.Color(255, 255, 255));
        NumerosLetras.setText("Numeros a Letras");
        NumerosLetras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumerosLetrasActionPerformed(evt);
            }
        });
        getContentPane().add(NumerosLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jButtonPagar.setBackground(new java.awt.Color(0, 51, 102));
        jButtonPagar.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonPagar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPagar.setText("Total a Pagar");
        jButtonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jButtonBillete.setBackground(new java.awt.Color(0, 51, 102));
        jButtonBillete.setFont(new java.awt.Font("DialogInput", 1, 17)); // NOI18N
        jButtonBillete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBillete.setText("Billetes y Monedas");
        jButtonBillete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBilleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBillete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabelParcial2.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabelParcial2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelParcial2.setText("Parcial 2");
        getContentPane().add(jLabelParcial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 60));

        jLabelFondoParcial2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dibujo Sobre Un Fondo Azul.jpg"))); // NOI18N
        getContentPane().add(jLabelFondoParcial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void   TrasparenciaBoton(){
        jButtonBack.setOpaque(false);
        jButtonBack.setContentAreaFilled(false);
        jButtonBack.setBorderPainted(false);
    }
    
    private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalidaActionPerformed

    private void jButtonTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTablasActionPerformed
        this.setVisible(false);
        P2_Tabla P2T = new P2_Tabla();
        P2T.setVisible(true);
    }//GEN-LAST:event_jButtonTablasActionPerformed

    private void jButtonFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFigurasActionPerformed
        this.setVisible(false);
        P2_Figuras P2F = new P2_Figuras();
        P2F.setVisible(true);
    }//GEN-LAST:event_jButtonFigurasActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.setVisible(false);
        PantallaMenu PM = new PantallaMenu();
        PM.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void NumerosLetrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumerosLetrasActionPerformed
        this.setVisible(false);
        P2_NumerosLetras P2NL = new P2_NumerosLetras();
        P2NL.setVisible(true);
    }//GEN-LAST:event_NumerosLetrasActionPerformed

    private void jButtonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarActionPerformed
        this.setVisible(false);
        P2_TotalPagar P2TP = new P2_TotalPagar();
        P2TP.setVisible(true);
    }//GEN-LAST:event_jButtonPagarActionPerformed

    private void jButtonBilleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBilleteActionPerformed
        this.setVisible(false);
        P2_BilletesMonedas P2BM = new P2_BilletesMonedas();
        P2BM.setVisible(true);
    }//GEN-LAST:event_jButtonBilleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaMenuParcial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaMenuParcial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaMenuParcial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaMenuParcial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaMenuParcial2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NumerosLetras;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBillete;
    private javax.swing.JButton jButtonFiguras;
    private javax.swing.JButton jButtonPagar;
    private javax.swing.JButton jButtonSalida;
    private javax.swing.JButton jButtonTablas;
    private javax.swing.JLabel jLabelFondoParcial2;
    private javax.swing.JLabel jLabelParcial2;
    // End of variables declaration//GEN-END:variables
}
