 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class PantallaMenu extends javax.swing.JFrame {

    /**
     * Creates new form PantallaProyecto
     */
    public PantallaMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButtonParcial1 = new javax.swing.JButton();
        jButtonParcial2 = new javax.swing.JButton();
        jButtonSalida = new javax.swing.JButton();
        jLabelMenuTitulo = new javax.swing.JLabel();
        jLabelFondoMenu = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonParcial1.setBackground(new java.awt.Color(0, 51, 102));
        jButtonParcial1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonParcial1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonParcial1.setText("Parcial 1");
        jButtonParcial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParcial1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonParcial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jButtonParcial2.setBackground(new java.awt.Color(0, 51, 102));
        jButtonParcial2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonParcial2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonParcial2.setText("Parcial 2");
        jButtonParcial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParcial2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonParcial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jButtonSalida.setBackground(new java.awt.Color(204, 0, 51));
        jButtonSalida.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonSalida.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalida.setText("X");
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabelMenuTitulo.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabelMenuTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenuTitulo.setText("MENÚ");
        getContentPane().add(jLabelMenuTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabelFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dibujo Sobre Un Fondo Azul.jpg"))); // NOI18N
        jLabelFondoMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButtonSalidaActionPerformed

    private void jButtonParcial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParcial1ActionPerformed
        this.setVisible(false);
        PantallaMenuParcial1 PMP1 = new PantallaMenuParcial1();
        PMP1.setVisible(true);
    }//GEN-LAST:event_jButtonParcial1ActionPerformed

    private void jButtonParcial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParcial2ActionPerformed
        this.setVisible(false);
        PantallaMenuParcial2 PMP2 = new PantallaMenuParcial2();
        PMP2.setVisible(true);
    }//GEN-LAST:event_jButtonParcial2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonParcial1;
    private javax.swing.JButton jButtonParcial2;
    private javax.swing.JButton jButtonSalida;
    private javax.swing.JLabel jLabelFondoMenu;
    private javax.swing.JLabel jLabelMenuTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
