/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class PantallaMenuParcial1 extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMenuParcial1
     */
    public PantallaMenuParcial1() {
        initComponents();
        this.setLocationRelativeTo(null);
        TrasparenciaBoton();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelParcial1 = new javax.swing.JLabel();
        jButtonDiasMeses = new javax.swing.JButton();
        jButtonCalculoDias = new javax.swing.JButton();
        jButtonNumerosRomanos = new javax.swing.JButton();
        jButtonOperadores = new javax.swing.JButton();
        jButtonCalificaciones = new javax.swing.JButton();
        jButtonValidacionFecha = new javax.swing.JButton();
        jButtonSalida = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelFondoParcial1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelParcial1.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabelParcial1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelParcial1.setText("Parcial 1");
        getContentPane().add(jLabelParcial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 60));

        jButtonDiasMeses.setBackground(new java.awt.Color(0, 51, 102));
        jButtonDiasMeses.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonDiasMeses.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDiasMeses.setText("Días entre Meses");
        jButtonDiasMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiasMesesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDiasMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jButtonCalculoDias.setBackground(new java.awt.Color(0, 51, 102));
        jButtonCalculoDias.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonCalculoDias.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalculoDias.setText("Calculo de Días");
        jButtonCalculoDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculoDiasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalculoDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jButtonNumerosRomanos.setBackground(new java.awt.Color(0, 51, 102));
        jButtonNumerosRomanos.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonNumerosRomanos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNumerosRomanos.setText("Numeros Romanos");
        jButtonNumerosRomanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumerosRomanosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNumerosRomanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jButtonOperadores.setBackground(new java.awt.Color(0, 51, 102));
        jButtonOperadores.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonOperadores.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOperadores.setText("Operadores");
        jButtonOperadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperadoresActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOperadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, 40));

        jButtonCalificaciones.setBackground(new java.awt.Color(0, 51, 102));
        jButtonCalificaciones.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonCalificaciones.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalificaciones.setText("Calificaciones");
        jButtonCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalificacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jButtonValidacionFecha.setBackground(new java.awt.Color(0, 51, 102));
        jButtonValidacionFecha.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jButtonValidacionFecha.setForeground(new java.awt.Color(255, 255, 255));
        jButtonValidacionFecha.setText("Validación de Fecha");
        jButtonValidacionFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidacionFechaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonValidacionFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jButtonSalida.setBackground(new java.awt.Color(204, 0, 51));
        jButtonSalida.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonSalida.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalida.setText("X");
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        jLabelFondoParcial1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dibujo Sobre Un Fondo Azul.jpg"))); // NOI18N
        jLabelFondoParcial1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelFondoParcial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void   TrasparenciaBoton(){
        jButtonBack.setOpaque(false);
        jButtonBack.setContentAreaFilled(false);
        jButtonBack.setBorderPainted(false);
    }
    
    private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalidaActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.setVisible(false);
        PantallaMenu PM = new PantallaMenu();
        PM.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonDiasMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiasMesesActionPerformed
        this.setVisible(false);
        P1_DiasMeses P1DM = new P1_DiasMeses();
        P1DM.setVisible(true);
    }//GEN-LAST:event_jButtonDiasMesesActionPerformed

    private void jButtonCalculoDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculoDiasActionPerformed
        this.setVisible(false);
        P1_CalculoDias P1CD = new P1_CalculoDias();
        P1CD.setVisible(true);
    }//GEN-LAST:event_jButtonCalculoDiasActionPerformed

    private void jButtonNumerosRomanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumerosRomanosActionPerformed
        this.setVisible(false);
        P1_NumerosRomanos P1NR = new P1_NumerosRomanos();
        P1NR.setVisible(true);
    }//GEN-LAST:event_jButtonNumerosRomanosActionPerformed

    private void jButtonOperadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperadoresActionPerformed
        this.setVisible(false);
        P1_Operadores P1O = new P1_Operadores();
        P1O.setVisible(true);
    }//GEN-LAST:event_jButtonOperadoresActionPerformed

    private void jButtonValidacionFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidacionFechaActionPerformed
        this.setVisible(false);
        P1_ValidacionFecha P1VF = new P1_ValidacionFecha();
        P1VF.setVisible(true);
    }//GEN-LAST:event_jButtonValidacionFechaActionPerformed

    private void jButtonCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalificacionesActionPerformed
        this.setVisible(false);
        P1_Calificaciones P1C = new P1_Calificaciones();
        P1C.setVisible(true);
    }//GEN-LAST:event_jButtonCalificacionesActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaMenuParcial1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCalculoDias;
    private javax.swing.JButton jButtonCalificaciones;
    private javax.swing.JButton jButtonDiasMeses;
    private javax.swing.JButton jButtonNumerosRomanos;
    private javax.swing.JButton jButtonOperadores;
    private javax.swing.JButton jButtonSalida;
    private javax.swing.JButton jButtonValidacionFecha;
    private javax.swing.JLabel jLabelFondoParcial1;
    private javax.swing.JLabel jLabelParcial1;
    // End of variables declaration//GEN-END:variables
}
